export const REQUEST_COORDS = 'REQUEST_COORDS';
export const REQUEST_COORDS_ERROR = 'REQUEST_COORDS_ERROR';
export const RECEIVE_COORDS = 'RECEIVE_COORDS';

export const REQUEST_WEEDMAPS_LISTINGS = 'REQUEST_WEEDMAPS_LISTINGS';
export const REQUEST_WEEDMAPS_LISTINGS_ERROR = 'REQUEST_WEEDMAPS_LISTINGS_ERROR';
export const RECEIVE_WEEDMAPS_LISTINGS = 'RECEIVE_WEEDMAPS_LISTINGS';

export const REQUEST_WEEDMAPS_LISTING_DETAILS = 'REQUEST_WEEDMAPS_LISTING_DETAILS';
export const REQUEST_WEEDMAPS_LISTING_DETAILS_ERROR = 'REQUEST_WEEDMAPS_LISTING_DETAILS_ERROR';
export const RECEIVE_WEEDMAPS_LISTING_DETAILS = 'RECEIVE_WEEDMAPS_LISTING_DETAILS';
